config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do 
    resources :todo_items do
  		member do 
  			patch :complete
  			patch :uncomplete
  		end
  	end
  end
  
  devise_scope :user do
    get "/sign-in" => "devise/sessions#new", :as => :login
  end

  root "todo_lists#index"


end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  default_scope {order priority: :desc}

  enum priority: [:low, :medium, :high]

  def completed?
  	!completed_at.blank?
  end

end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	has_many :todo_items, dependent: :destroy
	belongs_to :user
	def count_completed
		@todo_item = self.todo_items.all
		count = 0
		@todo_item.each do |item|
			if !item.completed_at.blank?
				count += 1
			end
		end
		return count
	end


	def item_completition
		division = (count_completed / self.todo_items.size.to_f) *100
		if division.nan?
			division = 0
		else
			division.to_i
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todo_list, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  
  def authenticate_user!
  	if user_signed_in?
  		super
  	else
  		redirect_to login_path
  	end
  end

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_todo_list
	before_action :set_todo_item, except: [:create]

	def create
		if todo_item_params[:content].blank?
			flash[:alert] = "Todo item could not be created with null value."
		else
			@todo_item = @todo_list.todo_items.create(todo_item_params)
		end
		redirect_to @todo_list
	end

	def destroy
		if @todo_item.destroy
			flash[:notice] = "Todo item was deleted."
		else
			flash[:alert] = "Todo item could not be deleted."
		end
		redirect_to @todo_list
	end

	def complete
		@todo_item.update_attribute(:completed_at, Time.now)
		redirect_to @todo_list, notice: "Todo item completed."
	end

	def uncomplete
		@todo_item.update_attribute(:completed_at, '')
		redirect_to @todo_list, notice: "Todo item uncompleted."
	end

	private

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def set_todo_item
		@todo_item = @todo_list.todo_items.find(params[:id])
	end

	def todo_item_params
		params[:todo_item].permit(:content, :priority)
	end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  def index
    @todo_lists = current_user.todo_list.all
  end

  def show
  end

  def new
    @todo_list = current_user.todo_list.build
  end

  def edit
  end

  def create
    @todo_list = current_user.todo_list.build(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Todo</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	</head>
	<body>

		<div class="container">
			<div style="position: fixed; z-index: 999; text-align: center;" class="messages">
				<% if notice %>
					<p id="notice"><%= notice %></p>
				<% elsif alert %>
					<p id="alert"><%= alert %></p>
				<% end %>
				<script type="text/javascript">
					$(document).ready (function(){
						$("#alert").fadeTo(2000, 5000).slideUp(500, function(){
							$("#alert").slideUp(500);
						});
						$("#notice").fadeTo(2000, 5000).slideUp(500, function(){
							$("#notice").slideUp(500);
						});
					});
				</script>
			</div>
			<%= yield %>
		</div>
	</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for ([@todo_list, @todo_list.todo_items.build]) do |f| %>
	<%= f.text_field :content, placeholder: "New Todo" %>
  	<%= f.select :priority, Priority.select_options %>

	<%= button_tag(type: 'submit') do %>
  		<span class="fa fa-plus fa-lg"></span> 
	<% end %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
	<% if todo_item.completed? %>
	<div class="complete">
		<%= link_to uncomplete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %> 
		<i style="opacity: 0.4;" class="fa fa-check"></i>
		<% end %>
	</div>
	<div class="priority">
		<p style="opacity: 0.4;">
			<% if todo_item.high? %>
			<%= content_tag :i, "", class: "fa fa-arrow-up" %>
			<% elsif todo_item.medium? %>
			<%= content_tag :i, "", class: "fa fa-minus" %>
			<% else %>
			<%= content_tag :i, "", class: "fa fa-arrow-down" %>
			<%end %>
		</p>
	</div>
	<div class="todo_item">
		<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
	</div>
	<div class="trash">
		<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure ?"} do %>
		<i class="fa fa-trash"></i>
		<% end %>
	</div>
	<% else %>
	<div class="complete">
		<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %> 
		<i class="fa fa-check"></i>
		<% end %>
	</div>
	<div class="priority">
		<p>
			<% if todo_item.high? %>
			<%= content_tag :i, "", class: "fa fa-arrow-up" %>
			<% elsif todo_item.medium? %>
			<%= content_tag :i, "", class: "fa fa-minus" %>
			<% else %>
			<%= content_tag :i, "", class: "fa fa-arrow-down" %>
			<%end %>
		</p>
	</div>
	<div class="todo_item">
		<p><%= todo_item.content %></p>
	</div>
	<div class="trash">
		<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure ?"} do %>
		<i class="fa fa-trash"></i>
		<% end %>
	</div>
	<% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h3>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/_progress_status.html.erb
<% item_completion = @todo_list.item_completition %>
<div class="progress">
	<div id="progress-status" role="progressbar" aria-valuenow="<%= item_completion %>" aria-valuemin="0" aria-valuemax="100" >
	</div>
	<script type="text/javascript">
		$(function() {
			$("#progress-status")
			.css("width", "<%= item_completion %>%")
			.text("<%= item_completion %>%");
		});
	</script>
</div>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Show', @todo_list %> |
	<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% if !user_signed_in? %>
	<div class="index_row clearfix">
		<p>
			<%= link_to "Sign up to save your todo list", new_user_session_path %>
		</p>
	</div>
<% else %>
	<p class="logout">Welcome  
		<%= current_user.email %> | 
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	</p>
	<% @todo_lists.each do |todo_list| %>
	  <div class="index_row clearfix">
	    <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
	    <p class="todo_list_sub_title"><%= todo_list.description %></p>
	  </div>
	<% end %>

	<div class="links">
		<%= link_to new_todo_list_path do %>
			<i class="fa fa-plus fa-lg"></i>
		<% end %>
	</div>
<% end %>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<div class="tools">
	<%= link_to todo_list_path(@todo_list), method: :delete, data: {confirm: "Are you sure ?"} do %>
		<i class="fa fa-trash fa-fw"></i>
	<% end %>
	<%= link_to edit_todo_list_path(@todo_list) do %>
		<i class="fa fa-pencil fa-fw"></i>
	<% end %>
</div>
<div>
	<h2 class="todo_list_title"><%= @todo_list.title %></h2>
	<p class="todo_list_sub_title"><%= @todo_list.description %></p>
</div>

<div id="todo_items_wrapper">
	<%= render "progress_status" %>
	<%= render @todo_list.todo_items %>
	<div id="form">
		<%= render "todo_items/form" %>
	</div>
</div>

<div class="links">
	<%= link_to 'Back', todo_lists_path %>
</div>